server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

weixin:
  config:
    originalid: gh_b565c73e3450
    token: b8b6
    app-id: wx01254df0def446cf
    app-secret: 453588981e0dc8110e10e5c9b81e3872
    template_id: uFLQ4b2okrD4l1Af6BzQ1qhI8yuY4QVhTb-j3876GY8

mybatis:
    mapper-locations: classpath:/mybatis/mapper/*.xml
    config-location: classpath:/mybatis/config/mybatis-config.xml

spring:
  redis:
    host: 127.0.0.1
    port: 16379
  datasource:
    username: root
    password: 12345l6
    url: jdbc:mysql://localhost:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat


logging:
  level:
    root: info
  config: classpath:logback-spring.xml


alipay:
  enabled: true
  app_id: 9021000157614611
  merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCJVcIL6Q65TCp5KY6Cn2ABqJ5xPJBJwC86luLOL7+PyLkG48tp6Hnz89uATOF+EVjHOkHrs5eY19sneGjTCTiPKQdb4Z7IXsGqW6K1hTWTa2Ffb+GPnc9KSfqCMNuRvXAfS9bRWH6U0kZ3bEK7cZZ2zl53NCXwvjM0UfSGPr8DKmd16yhmgACqD5mXoob7KNL15q/Kve9s2b2M4hXTByeI6tQ15VeAdqfSdp7TvkgOCdlvOO03FNCAzO9xMXW+l7mtwUDeOw0W0iB+dJvhXkL4mSH3ozyPXqa6JSDA08jOsiImKV1QKNpe4IVmmprCIhPKAhqikZYKYTWJftquNXwzAgMBAAECggEBAIWLTtYmGps05VhMgLekIsd6IBgcvHH63/IpJwM4ix5WIRYCDJs/5NbEGn34RI1CcQHKNK/uQ0vtGr6W59fO76DGVNGT48MT4V63HNFGZ4KiuF0FfmEZI6kppt9SgzCE9bJ5HLsVQoGUt9EJBRsgqR9+LX3cx8gCK+iEiTLBcRyxgT90wYh/y2SvMk6qh3bF29agHD1uDr2D2kxjpkaDUdWFH+c8s+DnGIsg0x24GFx7hnYUKndZViUR0bEAS56VOJ5uFIpeWTQnnXxluf2svkWSt9j7wU5r0gQjsR2JU09uYLyTY72fEiQQ3p5CqvyR7v/oa3BGYGzPc/nRrfsm+QECgYEAzIbmUQeNWo+PPj2dZmFH25rUrFAIruAnclhgDRnIXd89gREazqYbYepRSSfsYMtQZFaY+cvSpOZNMtUAFAt+KU8Z8Bj8xVBRxN5dpbBClwH/CPB27TDXjN2qrE8W0Vg4Fj3sV/RxxcBmOcFtc7WMujGd3db2VhZdqFpMl12PkdkCgYEAq+XeNYrG3PmNDgokJYt+ChLHgm2/bDV3pS/Cjbpti4oXShiHUxDhX4r59RMP1phzAJAAbDTNyB10p5Tbly3sKH1ZZ42zHVhVeyrXsPS6gcpxOvtEoNOlHWV8XKiFbmWx1b7D/ki+R7QgLHnqVehIDBMPKJQhpGY6Tx+emJ5FKusCgYEAq7VxtYOeo/I0s29tLt/rQS568HN85rxfwbr6YOVNd6oNa8dddzKzeIANYFq5NAZdZu/hHI6HOVP0agGzQCDp+Wpkf1OrG0i0bZC2lH0nWrodUHb5kWbZAHW1bVY09OqYo+u2+ZzKy9gcus5uwp8gF83CGNX5GAtM9CNjfAzblPkCgYEAotNEXrcrk5kWkZvtjVrKcsRDEzrdvaQPxvqscQ+MQEb3tInzdS1iLdw41HnP4Nfa50d//v8thUbRfwOz1Un8joXdsAc7CKrpnZeBY+8M03BtPQ9RfH29w1CkMii261GM2AixIibJhqYKa9a3r9QsmrNbAnb+PvlOdjBfS/VvUy0CgYBwNlKfcfz9vzBtwVdkofaEWztW+4k0rzp/1M/CNKxqOfMxD06QEMJvx+k1kKMZteaoANMRHSwJ4UoWPQyuxiks3X1I7AN3eo4jRmOfTaOKExMUGrqCtlCiORRIAb57je1x+SSfrOsyMeg0Iis4oCwO82W9fxPch+5+yaRcEV+Qvw==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1SHHhRfEjnCrVoVaVxUd0cHAAUjmesCfZYVEy2eRw5pgx4NIGyZJxy5xc9knoygzx74PJZ3+NGtbNmSGVsPfgUQy6ORP+3qvUK/0XtBnpai5puzx3OXNxFN0I7hukZEr7bT+H4s50iuerqvfN6N9LPMZ/EkZN6E7160NbWi03f03RihTTwTihM6hoadndAspDoF9JjUeERpTucOPObFjTV9EC7RK3RdIkmPUTLQMaSZs0CWyd2eK7GzirtRQzAjmGhV3809HYxDb9rFXQ6itb9eq+U3TmKBrYMMJcs/FVwdckzlMAwGZILGEfSoh1QSsRB7a0ODqJjGSbR8kVhiccQIDAQAB
  notify_url: http://3efef525.r31.cpolar.top/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
